### PR TITLE
changed .md endings to .html in basic_networking.md

### PR DESCRIPTION
**Pull request by hwoesner**

### CODE REVIEW

**Comment by KanjiMonster** [comment]
This is weird, according to https://github.blog/2016-12-05-relative-links-for-github-pages/ this should happen automatically.

**Comment by jklare** [comment]
This issue is valid, but i think the solution should be a different one. After reading a bit, i think we might need to specifically enable collections for relative links to work: https://github.com/benbalter/jekyll-relative-links#processing-collections

**Comment by ideaship** [comment]
> This issue is valid, but i think the solution should be a different one. After reading a bit, i think we might need to specifically enable collections for relative links to work: https://github.com/benbalter/jekyll-relative-links#processing-collections

The linked text is somewhat ambiguous, but it seems to suggest that without the plugins, relative links should never work with pages. And yet some do. For instance:
- frequently_asked_questions.md links to platform_configuration/switchcontrol.md#ttl-controls
- getting_started/connecting_to_the_switch.md: links to install_onie.md

So links to files in the same directory and relative links into sub-directories work (i.e., they do get rewritten to point to .html), unless the target file does not exist. Absolute paths do not seem to work, though. I wonder if relative paths can also go up (using ".."). If that were the case, then we could fix the remaining links.

**Comment by jklare** [comment]
this was fixed by #92

**Comment by jklare** [comment]
fixed in #92

**Pull request closed without merging**
