### PR TITLE
add downloads page

### PR DESCRIPTION
**Pull request by jklare**

### CODE REVIEW

**Comment by jklare** [comment]
waiting for: https://github.com/bisdn/bisdn.github.io/pull/157 to be testable

**Comment by jklare** [comment]
Screenshot 2022-08-23 at 16 44 18
like this @ideaship

**Comment by jklare** [comment]
Screenshot 2022-08-24 at 14 01 25
like this @ideaship

**Comment by ideaship** [comment]
LGTM.

**Pull request merged**
